<?xml version="1.0"?>

<robot name="box_robot" xmlns:xacro="http://ros.org/wiki/xacro">

    <property name="PI" value="3.1415926" />
   <!-- Define a number of dimensions using properties -->
   <property name="torso1_offset_x" value="0.10" />
   <property name="torso1_offset_y" value="0.15" />
   <property name="torso1_offset_z" value="0.20" /> <!--base_height/2+torso_height/2 -->
   <property name="torso2_offset_x" value="0.10" />
   <property name="torso2_offset_y" value="-0.15" />
   <property name="torso2_offset_z" value="0.20" /> <!--base_height/2+torso_height/2 -->
   <property name="torso3_offset_x" value="-0.10" />
   <property name="torso3_offset_y" value="0.15" />
   <property name="torso3_offset_z" value="0.20" /> <!--base_height/2+torso_height/2 -->
   <property name="torso4_offset_x" value="-0.10" />
   <property name="torso4_offset_y" value="-0.15" />
   <property name="torso4_offset_z" value="0.20" /> <!--base_height/2+torso_height/2 -->

   <property name="dobot_offset_x" value="0.125" />
   <property name="dobot_offset_y" value="0.0" />
   <property name="dobot_offset_z" value="0.32" />

   <!-- Include all component files -->
   <xacro:include filename="$(find dashgo_description)/urdf/dashgobase/materials.urdf.xacro" />
   <xacro:include filename="$(find dashgo_description)/urdf/dashgobase/base.urdf.xacro" />
   <xacro:include filename="$(find dashgo_description)/urdf/dashgobase/torso.urdf.xacro" />
   <xacro:include filename="$(find dobot)/urdf/dobot.urdf.xacro" />
   
   <!-- Add the base and wheels -->
   <base name="base" color="Black"/>
   
   <!-- Attach the torso -->
   <torso name="torso1" parent="base" color="Grey">
      <origin xyz="${torso1_offset_x} ${torso1_offset_y} ${torso1_offset_z}" rpy="0 0 0" />
   </torso>
   <torso name="torso2" parent="base" color="Grey">
      <origin xyz="${torso2_offset_x} ${torso2_offset_y} ${torso2_offset_z}" rpy="0 0 0" />
   </torso>
   <torso name="torso3" parent="base" color="Grey">
      <origin xyz="${torso3_offset_x} ${torso3_offset_y} ${torso3_offset_z}" rpy="0 0 0" />
   </torso>
   <torso name="torso4" parent="base" color="Grey">
      <origin xyz="${torso4_offset_x} ${torso4_offset_y} ${torso4_offset_z}" rpy="0 0 0" />
   </torso>

   <!-- <dobot name="dobot" parent="base" color="White"> -->
       <!-- <origin xyz="${dobot_offset_x} ${dobot_offset_y} ${dobot_offset_z}" rpy="0 0 0" /> -->
   <!-- </dobot> -->

   <link name="plane_link">
       <visual>
           <geometry>
               <cylinder length="0.002" radius="0.20" />
           </geometry>
           <material name="Grey" />
       </visual>
   </link>

   <joint name="plane_joint" type="fixed" >
       <origin xyz="0 0 0.32" rpy="0 0 0" />
       <parent link="base_link" />
       <child link="plane_link" />
   </joint>

   <link name="minipc_link">
       <visual>
           <geometry>
               <box size="0.17 0.20 0.05" />
           </geometry>
           <material name="Grey" />
       </visual>
       <inertial>
           <mass value="2.00" />
           <origin xyz="0 0 0" />
           <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0" izz="0.0001" />
       </inertial>
   </link>

   <joint name="minipc_joint" type="fixed">
       <origin xyz="0.00 0.00 0.105" rpy="0 0 0" />
       <parent link="base_link" />
       <child link="minipc_link" />
   </joint>

  <joint name="laser_plane_joint" type="fixed">
      <origin xyz="0.00 0.00 0.14" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="laser_plane_frame" />
  </joint>

  <link name="laser_plane_frame">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.1 0.07 0.07" />
      </geometry>
      <material name="Green" />
    </visual>
    <inertial>
      <mass value="0.000001" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
        iyy="0.0001" iyz="0.0"
        izz="0.0001" />
    </inertial>
  </link>

  <!-- <joint name="laser_joint" /> -->
  <!-- <link name="laser_frame" /> -->

  <link name="front_flag">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.05 0.05 0.001" />
        </geometry>
        <material name="TransparentGreen" />
      </visual>
  </link>

  <joint name="front_point_flag" type="fixed">
    <origin xyz="0.2 0 ${base_length/2}" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="front_flag" />
  </joint>

</robot>


